services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WapplerSystems\WsGuestbook\:
    resource: '../Classes/*'

  WapplerSystems\WsGuestbook\Form\Factory\GuestbookFormFactory:
    public: true
